

#define SAM3X8E_MCUCONF



/* EXT Driver */
#define SAM3X_PIOA_IRQ_PRIORITY 6
#define SAM3X_PIOB_IRQ_PRIORITY 6
#define SAM3X_PIOC_IRQ_PRIORITY 6
#define SAM3X_PIOD_IRQ_PRIORITY 6


/* DMA Driver */
#define SAM3X_DMA_IRQ_PRIORITY    4

/* SPI */
#define SAM3X_SPI_DMA_ERROR_HOOK(spip)      chSysHalt()
#define SAM3X_SPI_USE_SPI1                  TRUE
#define SAM3X_SPI1_DMA_RX					0
#define SAM3X_SPI1_DMA_TX					1
#define SAM3X_SPI_USE_SPI2                  FALSE

/* USART */
#define SAM3X_USART0_IRQ_PRIORITY 6
#define SAM3X_USART1_IRQ_PRIORITY 6
#define SAM3X_USART2_IRQ_PRIORITY 6
#define SAM3X_USART3_IRQ_PRIORITY 6
#define SAM3X_USART4_IRQ_PRIORITY 6

#define SAM3X_SERIAL_USE_SD1    TRUE
#define SAM3X_SERIAL_USE_SD2    TRUE
#define SAM3X_SERIAL_USE_SD3    FALSE
#define SAM3X_SERIAL_USE_SD4    TRUE
#define SAM3X_SERIAL_USE_SD5    TRUE


/*ADC */
#define SAM3X_ADC_USE_ADC1     TRUE
#define SAM3X_ADC_IRQ_PRIORITY      6


/*I2C*/
#define SAM3X_I2C_USE_I2C1     TRUE
#define SAM3X_I2C_USE_I2C2     FALSE
#define SAM3X_I2C_IRQ_PRIORITY      6


/*UART*/
#define SAM3X_UART_USE_UART1 FALSE
#define SAM3X_UART_RX_BUFSIZE 64
#define SAM3X_UART_TX_BUFSIZE 64
#define SAM3X_UART_IRQ_PRIORITY 6

/*PWM*/
#define SAM3X_PWM_USE_PWM TRUE