#List of external drivers
BOARD_EXT_DRIVERS =

#Macro to be passed to compiler via -D directive
BOARD_DEFINES:= VM_UPLOAD_INTERFACE=0 VM_IRQS=8 VM_PRE_UPLOAD_WAIT=2000 VM_UPLOAD_TIMEOUT=5000 VM_STDOUT=0 VM_STDERR=1 VM_STDIN=0 VM_BOARD=\"spark_v2\" VM_ARCH=\"arm.cortex-m3\" VM_RAM=20480 VM_UPLOAD_PROTO_ALTERNATE VM_NO_MUTEXES=1 VM_KICK_IWDG=1 VM_NO_MAILBOXES=1


BOARD_DEFINES+= VM_UPLOADED_BYTECODE